spring:
  application:
    name: hello-spring-cloud-config
  # 将git密码引入
  profiles:
    include: git
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/NJAUzhangwenjun/spring-cloud-config.git
          search-paths: respo
#          username:
#          password:

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
