spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    #以 /api/a 开头的请求都转发给 hello-spring-cloud-web-admin-ribbon 服务
    #以 /api/b 开头的请求都转发给 hello-spring-cloud-web-admin-feign 服务
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-feign
